---
- hosts: test
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: True

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: latest
      force_apt_get: yes
    vars:
      packages:
      - software-properties-common
      - apt-transport-https
      - curl
      - ca-certificates
      - gnupg-agent
      - software-properties-common

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes
      force_apt_get: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
